# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.25.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.25.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bhayes/repos/mbientlab/MetaWear-SDK-Cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bhayes/repos/mbientlab/MetaWear-SDK-Cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.25.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.25.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.25.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.25.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.25.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.25.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.25.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.25.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bhayes/repos/mbientlab/MetaWear-SDK-Cpp/CMakeFiles /Users/bhayes/repos/mbientlab/MetaWear-SDK-Cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bhayes/repos/mbientlab/MetaWear-SDK-Cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named metawear

# Build rule for target.
metawear: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 metawear
.PHONY : metawear

# fast build rule for target.
metawear/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/build
.PHONY : metawear/fast

src/metawear/core/cpp/anonymous_datasignal.o: src/metawear/core/cpp/anonymous_datasignal.cpp.o
.PHONY : src/metawear/core/cpp/anonymous_datasignal.o

# target to build an object file
src/metawear/core/cpp/anonymous_datasignal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/anonymous_datasignal.cpp.o
.PHONY : src/metawear/core/cpp/anonymous_datasignal.cpp.o

src/metawear/core/cpp/anonymous_datasignal.i: src/metawear/core/cpp/anonymous_datasignal.cpp.i
.PHONY : src/metawear/core/cpp/anonymous_datasignal.i

# target to preprocess a source file
src/metawear/core/cpp/anonymous_datasignal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/anonymous_datasignal.cpp.i
.PHONY : src/metawear/core/cpp/anonymous_datasignal.cpp.i

src/metawear/core/cpp/anonymous_datasignal.s: src/metawear/core/cpp/anonymous_datasignal.cpp.s
.PHONY : src/metawear/core/cpp/anonymous_datasignal.s

# target to generate assembly for a file
src/metawear/core/cpp/anonymous_datasignal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/anonymous_datasignal.cpp.s
.PHONY : src/metawear/core/cpp/anonymous_datasignal.cpp.s

src/metawear/core/cpp/datasignal.o: src/metawear/core/cpp/datasignal.cpp.o
.PHONY : src/metawear/core/cpp/datasignal.o

# target to build an object file
src/metawear/core/cpp/datasignal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/datasignal.cpp.o
.PHONY : src/metawear/core/cpp/datasignal.cpp.o

src/metawear/core/cpp/datasignal.i: src/metawear/core/cpp/datasignal.cpp.i
.PHONY : src/metawear/core/cpp/datasignal.i

# target to preprocess a source file
src/metawear/core/cpp/datasignal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/datasignal.cpp.i
.PHONY : src/metawear/core/cpp/datasignal.cpp.i

src/metawear/core/cpp/datasignal.s: src/metawear/core/cpp/datasignal.cpp.s
.PHONY : src/metawear/core/cpp/datasignal.s

# target to generate assembly for a file
src/metawear/core/cpp/datasignal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/datasignal.cpp.s
.PHONY : src/metawear/core/cpp/datasignal.cpp.s

src/metawear/core/cpp/debug.o: src/metawear/core/cpp/debug.cpp.o
.PHONY : src/metawear/core/cpp/debug.o

# target to build an object file
src/metawear/core/cpp/debug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/debug.cpp.o
.PHONY : src/metawear/core/cpp/debug.cpp.o

src/metawear/core/cpp/debug.i: src/metawear/core/cpp/debug.cpp.i
.PHONY : src/metawear/core/cpp/debug.i

# target to preprocess a source file
src/metawear/core/cpp/debug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/debug.cpp.i
.PHONY : src/metawear/core/cpp/debug.cpp.i

src/metawear/core/cpp/debug.s: src/metawear/core/cpp/debug.cpp.s
.PHONY : src/metawear/core/cpp/debug.s

# target to generate assembly for a file
src/metawear/core/cpp/debug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/debug.cpp.s
.PHONY : src/metawear/core/cpp/debug.cpp.s

src/metawear/core/cpp/event.o: src/metawear/core/cpp/event.cpp.o
.PHONY : src/metawear/core/cpp/event.o

# target to build an object file
src/metawear/core/cpp/event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/event.cpp.o
.PHONY : src/metawear/core/cpp/event.cpp.o

src/metawear/core/cpp/event.i: src/metawear/core/cpp/event.cpp.i
.PHONY : src/metawear/core/cpp/event.i

# target to preprocess a source file
src/metawear/core/cpp/event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/event.cpp.i
.PHONY : src/metawear/core/cpp/event.cpp.i

src/metawear/core/cpp/event.s: src/metawear/core/cpp/event.cpp.s
.PHONY : src/metawear/core/cpp/event.s

# target to generate assembly for a file
src/metawear/core/cpp/event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/event.cpp.s
.PHONY : src/metawear/core/cpp/event.cpp.s

src/metawear/core/cpp/logging.o: src/metawear/core/cpp/logging.cpp.o
.PHONY : src/metawear/core/cpp/logging.o

# target to build an object file
src/metawear/core/cpp/logging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/logging.cpp.o
.PHONY : src/metawear/core/cpp/logging.cpp.o

src/metawear/core/cpp/logging.i: src/metawear/core/cpp/logging.cpp.i
.PHONY : src/metawear/core/cpp/logging.i

# target to preprocess a source file
src/metawear/core/cpp/logging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/logging.cpp.i
.PHONY : src/metawear/core/cpp/logging.cpp.i

src/metawear/core/cpp/logging.s: src/metawear/core/cpp/logging.cpp.s
.PHONY : src/metawear/core/cpp/logging.s

# target to generate assembly for a file
src/metawear/core/cpp/logging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/logging.cpp.s
.PHONY : src/metawear/core/cpp/logging.cpp.s

src/metawear/core/cpp/macro.o: src/metawear/core/cpp/macro.cpp.o
.PHONY : src/metawear/core/cpp/macro.o

# target to build an object file
src/metawear/core/cpp/macro.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/macro.cpp.o
.PHONY : src/metawear/core/cpp/macro.cpp.o

src/metawear/core/cpp/macro.i: src/metawear/core/cpp/macro.cpp.i
.PHONY : src/metawear/core/cpp/macro.i

# target to preprocess a source file
src/metawear/core/cpp/macro.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/macro.cpp.i
.PHONY : src/metawear/core/cpp/macro.cpp.i

src/metawear/core/cpp/macro.s: src/metawear/core/cpp/macro.cpp.s
.PHONY : src/metawear/core/cpp/macro.s

# target to generate assembly for a file
src/metawear/core/cpp/macro.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/macro.cpp.s
.PHONY : src/metawear/core/cpp/macro.cpp.s

src/metawear/core/cpp/moduleinfo.o: src/metawear/core/cpp/moduleinfo.cpp.o
.PHONY : src/metawear/core/cpp/moduleinfo.o

# target to build an object file
src/metawear/core/cpp/moduleinfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/moduleinfo.cpp.o
.PHONY : src/metawear/core/cpp/moduleinfo.cpp.o

src/metawear/core/cpp/moduleinfo.i: src/metawear/core/cpp/moduleinfo.cpp.i
.PHONY : src/metawear/core/cpp/moduleinfo.i

# target to preprocess a source file
src/metawear/core/cpp/moduleinfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/moduleinfo.cpp.i
.PHONY : src/metawear/core/cpp/moduleinfo.cpp.i

src/metawear/core/cpp/moduleinfo.s: src/metawear/core/cpp/moduleinfo.cpp.s
.PHONY : src/metawear/core/cpp/moduleinfo.s

# target to generate assembly for a file
src/metawear/core/cpp/moduleinfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/moduleinfo.cpp.s
.PHONY : src/metawear/core/cpp/moduleinfo.cpp.s

src/metawear/core/cpp/responseheader.o: src/metawear/core/cpp/responseheader.cpp.o
.PHONY : src/metawear/core/cpp/responseheader.o

# target to build an object file
src/metawear/core/cpp/responseheader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/responseheader.cpp.o
.PHONY : src/metawear/core/cpp/responseheader.cpp.o

src/metawear/core/cpp/responseheader.i: src/metawear/core/cpp/responseheader.cpp.i
.PHONY : src/metawear/core/cpp/responseheader.i

# target to preprocess a source file
src/metawear/core/cpp/responseheader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/responseheader.cpp.i
.PHONY : src/metawear/core/cpp/responseheader.cpp.i

src/metawear/core/cpp/responseheader.s: src/metawear/core/cpp/responseheader.cpp.s
.PHONY : src/metawear/core/cpp/responseheader.s

# target to generate assembly for a file
src/metawear/core/cpp/responseheader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/responseheader.cpp.s
.PHONY : src/metawear/core/cpp/responseheader.cpp.s

src/metawear/core/cpp/settings.o: src/metawear/core/cpp/settings.cpp.o
.PHONY : src/metawear/core/cpp/settings.o

# target to build an object file
src/metawear/core/cpp/settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/settings.cpp.o
.PHONY : src/metawear/core/cpp/settings.cpp.o

src/metawear/core/cpp/settings.i: src/metawear/core/cpp/settings.cpp.i
.PHONY : src/metawear/core/cpp/settings.i

# target to preprocess a source file
src/metawear/core/cpp/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/settings.cpp.i
.PHONY : src/metawear/core/cpp/settings.cpp.i

src/metawear/core/cpp/settings.s: src/metawear/core/cpp/settings.cpp.s
.PHONY : src/metawear/core/cpp/settings.s

# target to generate assembly for a file
src/metawear/core/cpp/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/settings.cpp.s
.PHONY : src/metawear/core/cpp/settings.cpp.s

src/metawear/core/cpp/timer.o: src/metawear/core/cpp/timer.cpp.o
.PHONY : src/metawear/core/cpp/timer.o

# target to build an object file
src/metawear/core/cpp/timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/timer.cpp.o
.PHONY : src/metawear/core/cpp/timer.cpp.o

src/metawear/core/cpp/timer.i: src/metawear/core/cpp/timer.cpp.i
.PHONY : src/metawear/core/cpp/timer.i

# target to preprocess a source file
src/metawear/core/cpp/timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/timer.cpp.i
.PHONY : src/metawear/core/cpp/timer.cpp.i

src/metawear/core/cpp/timer.s: src/metawear/core/cpp/timer.cpp.s
.PHONY : src/metawear/core/cpp/timer.s

# target to generate assembly for a file
src/metawear/core/cpp/timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/timer.cpp.s
.PHONY : src/metawear/core/cpp/timer.cpp.s

src/metawear/core/cpp/version.o: src/metawear/core/cpp/version.cpp.o
.PHONY : src/metawear/core/cpp/version.o

# target to build an object file
src/metawear/core/cpp/version.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/version.cpp.o
.PHONY : src/metawear/core/cpp/version.cpp.o

src/metawear/core/cpp/version.i: src/metawear/core/cpp/version.cpp.i
.PHONY : src/metawear/core/cpp/version.i

# target to preprocess a source file
src/metawear/core/cpp/version.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/version.cpp.i
.PHONY : src/metawear/core/cpp/version.cpp.i

src/metawear/core/cpp/version.s: src/metawear/core/cpp/version.cpp.s
.PHONY : src/metawear/core/cpp/version.s

# target to generate assembly for a file
src/metawear/core/cpp/version.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/core/cpp/version.cpp.s
.PHONY : src/metawear/core/cpp/version.cpp.s

src/metawear/dfu/cpp/dfu_operations.o: src/metawear/dfu/cpp/dfu_operations.cpp.o
.PHONY : src/metawear/dfu/cpp/dfu_operations.o

# target to build an object file
src/metawear/dfu/cpp/dfu_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/dfu/cpp/dfu_operations.cpp.o
.PHONY : src/metawear/dfu/cpp/dfu_operations.cpp.o

src/metawear/dfu/cpp/dfu_operations.i: src/metawear/dfu/cpp/dfu_operations.cpp.i
.PHONY : src/metawear/dfu/cpp/dfu_operations.i

# target to preprocess a source file
src/metawear/dfu/cpp/dfu_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/dfu/cpp/dfu_operations.cpp.i
.PHONY : src/metawear/dfu/cpp/dfu_operations.cpp.i

src/metawear/dfu/cpp/dfu_operations.s: src/metawear/dfu/cpp/dfu_operations.cpp.s
.PHONY : src/metawear/dfu/cpp/dfu_operations.s

# target to generate assembly for a file
src/metawear/dfu/cpp/dfu_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/dfu/cpp/dfu_operations.cpp.s
.PHONY : src/metawear/dfu/cpp/dfu_operations.cpp.s

src/metawear/dfu/cpp/dfu_operations_details.o: src/metawear/dfu/cpp/dfu_operations_details.cpp.o
.PHONY : src/metawear/dfu/cpp/dfu_operations_details.o

# target to build an object file
src/metawear/dfu/cpp/dfu_operations_details.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/dfu/cpp/dfu_operations_details.cpp.o
.PHONY : src/metawear/dfu/cpp/dfu_operations_details.cpp.o

src/metawear/dfu/cpp/dfu_operations_details.i: src/metawear/dfu/cpp/dfu_operations_details.cpp.i
.PHONY : src/metawear/dfu/cpp/dfu_operations_details.i

# target to preprocess a source file
src/metawear/dfu/cpp/dfu_operations_details.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/dfu/cpp/dfu_operations_details.cpp.i
.PHONY : src/metawear/dfu/cpp/dfu_operations_details.cpp.i

src/metawear/dfu/cpp/dfu_operations_details.s: src/metawear/dfu/cpp/dfu_operations_details.cpp.s
.PHONY : src/metawear/dfu/cpp/dfu_operations_details.s

# target to generate assembly for a file
src/metawear/dfu/cpp/dfu_operations_details.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/dfu/cpp/dfu_operations_details.cpp.s
.PHONY : src/metawear/dfu/cpp/dfu_operations_details.cpp.s

src/metawear/dfu/cpp/dfu_utility.o: src/metawear/dfu/cpp/dfu_utility.cpp.o
.PHONY : src/metawear/dfu/cpp/dfu_utility.o

# target to build an object file
src/metawear/dfu/cpp/dfu_utility.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/dfu/cpp/dfu_utility.cpp.o
.PHONY : src/metawear/dfu/cpp/dfu_utility.cpp.o

src/metawear/dfu/cpp/dfu_utility.i: src/metawear/dfu/cpp/dfu_utility.cpp.i
.PHONY : src/metawear/dfu/cpp/dfu_utility.i

# target to preprocess a source file
src/metawear/dfu/cpp/dfu_utility.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/dfu/cpp/dfu_utility.cpp.i
.PHONY : src/metawear/dfu/cpp/dfu_utility.cpp.i

src/metawear/dfu/cpp/dfu_utility.s: src/metawear/dfu/cpp/dfu_utility.cpp.s
.PHONY : src/metawear/dfu/cpp/dfu_utility.s

# target to generate assembly for a file
src/metawear/dfu/cpp/dfu_utility.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/dfu/cpp/dfu_utility.cpp.s
.PHONY : src/metawear/dfu/cpp/dfu_utility.cpp.s

src/metawear/dfu/cpp/file_operations.o: src/metawear/dfu/cpp/file_operations.cpp.o
.PHONY : src/metawear/dfu/cpp/file_operations.o

# target to build an object file
src/metawear/dfu/cpp/file_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/dfu/cpp/file_operations.cpp.o
.PHONY : src/metawear/dfu/cpp/file_operations.cpp.o

src/metawear/dfu/cpp/file_operations.i: src/metawear/dfu/cpp/file_operations.cpp.i
.PHONY : src/metawear/dfu/cpp/file_operations.i

# target to preprocess a source file
src/metawear/dfu/cpp/file_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/dfu/cpp/file_operations.cpp.i
.PHONY : src/metawear/dfu/cpp/file_operations.cpp.i

src/metawear/dfu/cpp/file_operations.s: src/metawear/dfu/cpp/file_operations.cpp.s
.PHONY : src/metawear/dfu/cpp/file_operations.s

# target to generate assembly for a file
src/metawear/dfu/cpp/file_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/dfu/cpp/file_operations.cpp.s
.PHONY : src/metawear/dfu/cpp/file_operations.cpp.s

src/metawear/dfu/cpp/miniz.o: src/metawear/dfu/cpp/miniz.cpp.o
.PHONY : src/metawear/dfu/cpp/miniz.o

# target to build an object file
src/metawear/dfu/cpp/miniz.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/dfu/cpp/miniz.cpp.o
.PHONY : src/metawear/dfu/cpp/miniz.cpp.o

src/metawear/dfu/cpp/miniz.i: src/metawear/dfu/cpp/miniz.cpp.i
.PHONY : src/metawear/dfu/cpp/miniz.i

# target to preprocess a source file
src/metawear/dfu/cpp/miniz.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/dfu/cpp/miniz.cpp.i
.PHONY : src/metawear/dfu/cpp/miniz.cpp.i

src/metawear/dfu/cpp/miniz.s: src/metawear/dfu/cpp/miniz.cpp.s
.PHONY : src/metawear/dfu/cpp/miniz.s

# target to generate assembly for a file
src/metawear/dfu/cpp/miniz.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/dfu/cpp/miniz.cpp.s
.PHONY : src/metawear/dfu/cpp/miniz.cpp.s

src/metawear/impl/cpp/datainterpreter.o: src/metawear/impl/cpp/datainterpreter.cpp.o
.PHONY : src/metawear/impl/cpp/datainterpreter.o

# target to build an object file
src/metawear/impl/cpp/datainterpreter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/impl/cpp/datainterpreter.cpp.o
.PHONY : src/metawear/impl/cpp/datainterpreter.cpp.o

src/metawear/impl/cpp/datainterpreter.i: src/metawear/impl/cpp/datainterpreter.cpp.i
.PHONY : src/metawear/impl/cpp/datainterpreter.i

# target to preprocess a source file
src/metawear/impl/cpp/datainterpreter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/impl/cpp/datainterpreter.cpp.i
.PHONY : src/metawear/impl/cpp/datainterpreter.cpp.i

src/metawear/impl/cpp/datainterpreter.s: src/metawear/impl/cpp/datainterpreter.cpp.s
.PHONY : src/metawear/impl/cpp/datainterpreter.s

# target to generate assembly for a file
src/metawear/impl/cpp/datainterpreter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/impl/cpp/datainterpreter.cpp.s
.PHONY : src/metawear/impl/cpp/datainterpreter.cpp.s

src/metawear/impl/cpp/metawearboard.o: src/metawear/impl/cpp/metawearboard.cpp.o
.PHONY : src/metawear/impl/cpp/metawearboard.o

# target to build an object file
src/metawear/impl/cpp/metawearboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/impl/cpp/metawearboard.cpp.o
.PHONY : src/metawear/impl/cpp/metawearboard.cpp.o

src/metawear/impl/cpp/metawearboard.i: src/metawear/impl/cpp/metawearboard.cpp.i
.PHONY : src/metawear/impl/cpp/metawearboard.i

# target to preprocess a source file
src/metawear/impl/cpp/metawearboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/impl/cpp/metawearboard.cpp.i
.PHONY : src/metawear/impl/cpp/metawearboard.cpp.i

src/metawear/impl/cpp/metawearboard.s: src/metawear/impl/cpp/metawearboard.cpp.s
.PHONY : src/metawear/impl/cpp/metawearboard.s

# target to generate assembly for a file
src/metawear/impl/cpp/metawearboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/impl/cpp/metawearboard.cpp.s
.PHONY : src/metawear/impl/cpp/metawearboard.cpp.s

src/metawear/peripheral/cpp/haptic.o: src/metawear/peripheral/cpp/haptic.cpp.o
.PHONY : src/metawear/peripheral/cpp/haptic.o

# target to build an object file
src/metawear/peripheral/cpp/haptic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/peripheral/cpp/haptic.cpp.o
.PHONY : src/metawear/peripheral/cpp/haptic.cpp.o

src/metawear/peripheral/cpp/haptic.i: src/metawear/peripheral/cpp/haptic.cpp.i
.PHONY : src/metawear/peripheral/cpp/haptic.i

# target to preprocess a source file
src/metawear/peripheral/cpp/haptic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/peripheral/cpp/haptic.cpp.i
.PHONY : src/metawear/peripheral/cpp/haptic.cpp.i

src/metawear/peripheral/cpp/haptic.s: src/metawear/peripheral/cpp/haptic.cpp.s
.PHONY : src/metawear/peripheral/cpp/haptic.s

# target to generate assembly for a file
src/metawear/peripheral/cpp/haptic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/peripheral/cpp/haptic.cpp.s
.PHONY : src/metawear/peripheral/cpp/haptic.cpp.s

src/metawear/peripheral/cpp/ibeacon.o: src/metawear/peripheral/cpp/ibeacon.cpp.o
.PHONY : src/metawear/peripheral/cpp/ibeacon.o

# target to build an object file
src/metawear/peripheral/cpp/ibeacon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/peripheral/cpp/ibeacon.cpp.o
.PHONY : src/metawear/peripheral/cpp/ibeacon.cpp.o

src/metawear/peripheral/cpp/ibeacon.i: src/metawear/peripheral/cpp/ibeacon.cpp.i
.PHONY : src/metawear/peripheral/cpp/ibeacon.i

# target to preprocess a source file
src/metawear/peripheral/cpp/ibeacon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/peripheral/cpp/ibeacon.cpp.i
.PHONY : src/metawear/peripheral/cpp/ibeacon.cpp.i

src/metawear/peripheral/cpp/ibeacon.s: src/metawear/peripheral/cpp/ibeacon.cpp.s
.PHONY : src/metawear/peripheral/cpp/ibeacon.s

# target to generate assembly for a file
src/metawear/peripheral/cpp/ibeacon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/peripheral/cpp/ibeacon.cpp.s
.PHONY : src/metawear/peripheral/cpp/ibeacon.cpp.s

src/metawear/peripheral/cpp/led.o: src/metawear/peripheral/cpp/led.cpp.o
.PHONY : src/metawear/peripheral/cpp/led.o

# target to build an object file
src/metawear/peripheral/cpp/led.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/peripheral/cpp/led.cpp.o
.PHONY : src/metawear/peripheral/cpp/led.cpp.o

src/metawear/peripheral/cpp/led.i: src/metawear/peripheral/cpp/led.cpp.i
.PHONY : src/metawear/peripheral/cpp/led.i

# target to preprocess a source file
src/metawear/peripheral/cpp/led.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/peripheral/cpp/led.cpp.i
.PHONY : src/metawear/peripheral/cpp/led.cpp.i

src/metawear/peripheral/cpp/led.s: src/metawear/peripheral/cpp/led.cpp.s
.PHONY : src/metawear/peripheral/cpp/led.s

# target to generate assembly for a file
src/metawear/peripheral/cpp/led.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/peripheral/cpp/led.cpp.s
.PHONY : src/metawear/peripheral/cpp/led.cpp.s

src/metawear/platform/cpp/async_creator.o: src/metawear/platform/cpp/async_creator.cpp.o
.PHONY : src/metawear/platform/cpp/async_creator.o

# target to build an object file
src/metawear/platform/cpp/async_creator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/platform/cpp/async_creator.cpp.o
.PHONY : src/metawear/platform/cpp/async_creator.cpp.o

src/metawear/platform/cpp/async_creator.i: src/metawear/platform/cpp/async_creator.cpp.i
.PHONY : src/metawear/platform/cpp/async_creator.i

# target to preprocess a source file
src/metawear/platform/cpp/async_creator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/platform/cpp/async_creator.cpp.i
.PHONY : src/metawear/platform/cpp/async_creator.cpp.i

src/metawear/platform/cpp/async_creator.s: src/metawear/platform/cpp/async_creator.cpp.s
.PHONY : src/metawear/platform/cpp/async_creator.s

# target to generate assembly for a file
src/metawear/platform/cpp/async_creator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/platform/cpp/async_creator.cpp.s
.PHONY : src/metawear/platform/cpp/async_creator.cpp.s

src/metawear/platform/cpp/memory.o: src/metawear/platform/cpp/memory.cpp.o
.PHONY : src/metawear/platform/cpp/memory.o

# target to build an object file
src/metawear/platform/cpp/memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/platform/cpp/memory.cpp.o
.PHONY : src/metawear/platform/cpp/memory.cpp.o

src/metawear/platform/cpp/memory.i: src/metawear/platform/cpp/memory.cpp.i
.PHONY : src/metawear/platform/cpp/memory.i

# target to preprocess a source file
src/metawear/platform/cpp/memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/platform/cpp/memory.cpp.i
.PHONY : src/metawear/platform/cpp/memory.cpp.i

src/metawear/platform/cpp/memory.s: src/metawear/platform/cpp/memory.cpp.s
.PHONY : src/metawear/platform/cpp/memory.s

# target to generate assembly for a file
src/metawear/platform/cpp/memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/platform/cpp/memory.cpp.s
.PHONY : src/metawear/platform/cpp/memory.cpp.s

src/metawear/platform/cpp/task.o: src/metawear/platform/cpp/task.cpp.o
.PHONY : src/metawear/platform/cpp/task.o

# target to build an object file
src/metawear/platform/cpp/task.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/platform/cpp/task.cpp.o
.PHONY : src/metawear/platform/cpp/task.cpp.o

src/metawear/platform/cpp/task.i: src/metawear/platform/cpp/task.cpp.i
.PHONY : src/metawear/platform/cpp/task.i

# target to preprocess a source file
src/metawear/platform/cpp/task.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/platform/cpp/task.cpp.i
.PHONY : src/metawear/platform/cpp/task.cpp.i

src/metawear/platform/cpp/task.s: src/metawear/platform/cpp/task.cpp.s
.PHONY : src/metawear/platform/cpp/task.s

# target to generate assembly for a file
src/metawear/platform/cpp/task.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/platform/cpp/task.cpp.s
.PHONY : src/metawear/platform/cpp/task.cpp.s

src/metawear/platform/cpp/threadpool.o: src/metawear/platform/cpp/threadpool.cpp.o
.PHONY : src/metawear/platform/cpp/threadpool.o

# target to build an object file
src/metawear/platform/cpp/threadpool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/platform/cpp/threadpool.cpp.o
.PHONY : src/metawear/platform/cpp/threadpool.cpp.o

src/metawear/platform/cpp/threadpool.i: src/metawear/platform/cpp/threadpool.cpp.i
.PHONY : src/metawear/platform/cpp/threadpool.i

# target to preprocess a source file
src/metawear/platform/cpp/threadpool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/platform/cpp/threadpool.cpp.i
.PHONY : src/metawear/platform/cpp/threadpool.cpp.i

src/metawear/platform/cpp/threadpool.s: src/metawear/platform/cpp/threadpool.cpp.s
.PHONY : src/metawear/platform/cpp/threadpool.s

# target to generate assembly for a file
src/metawear/platform/cpp/threadpool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/platform/cpp/threadpool.cpp.s
.PHONY : src/metawear/platform/cpp/threadpool.cpp.s

src/metawear/processor/cpp/dataprocessor.o: src/metawear/processor/cpp/dataprocessor.cpp.o
.PHONY : src/metawear/processor/cpp/dataprocessor.o

# target to build an object file
src/metawear/processor/cpp/dataprocessor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/processor/cpp/dataprocessor.cpp.o
.PHONY : src/metawear/processor/cpp/dataprocessor.cpp.o

src/metawear/processor/cpp/dataprocessor.i: src/metawear/processor/cpp/dataprocessor.cpp.i
.PHONY : src/metawear/processor/cpp/dataprocessor.i

# target to preprocess a source file
src/metawear/processor/cpp/dataprocessor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/processor/cpp/dataprocessor.cpp.i
.PHONY : src/metawear/processor/cpp/dataprocessor.cpp.i

src/metawear/processor/cpp/dataprocessor.s: src/metawear/processor/cpp/dataprocessor.cpp.s
.PHONY : src/metawear/processor/cpp/dataprocessor.s

# target to generate assembly for a file
src/metawear/processor/cpp/dataprocessor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/processor/cpp/dataprocessor.cpp.s
.PHONY : src/metawear/processor/cpp/dataprocessor.cpp.s

src/metawear/processor/cpp/dataprocessor_config.o: src/metawear/processor/cpp/dataprocessor_config.cpp.o
.PHONY : src/metawear/processor/cpp/dataprocessor_config.o

# target to build an object file
src/metawear/processor/cpp/dataprocessor_config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/processor/cpp/dataprocessor_config.cpp.o
.PHONY : src/metawear/processor/cpp/dataprocessor_config.cpp.o

src/metawear/processor/cpp/dataprocessor_config.i: src/metawear/processor/cpp/dataprocessor_config.cpp.i
.PHONY : src/metawear/processor/cpp/dataprocessor_config.i

# target to preprocess a source file
src/metawear/processor/cpp/dataprocessor_config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/processor/cpp/dataprocessor_config.cpp.i
.PHONY : src/metawear/processor/cpp/dataprocessor_config.cpp.i

src/metawear/processor/cpp/dataprocessor_config.s: src/metawear/processor/cpp/dataprocessor_config.cpp.s
.PHONY : src/metawear/processor/cpp/dataprocessor_config.s

# target to generate assembly for a file
src/metawear/processor/cpp/dataprocessor_config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/processor/cpp/dataprocessor_config.cpp.s
.PHONY : src/metawear/processor/cpp/dataprocessor_config.cpp.s

src/metawear/sensor/cpp/accelerometer.o: src/metawear/sensor/cpp/accelerometer.cpp.o
.PHONY : src/metawear/sensor/cpp/accelerometer.o

# target to build an object file
src/metawear/sensor/cpp/accelerometer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/accelerometer.cpp.o
.PHONY : src/metawear/sensor/cpp/accelerometer.cpp.o

src/metawear/sensor/cpp/accelerometer.i: src/metawear/sensor/cpp/accelerometer.cpp.i
.PHONY : src/metawear/sensor/cpp/accelerometer.i

# target to preprocess a source file
src/metawear/sensor/cpp/accelerometer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/accelerometer.cpp.i
.PHONY : src/metawear/sensor/cpp/accelerometer.cpp.i

src/metawear/sensor/cpp/accelerometer.s: src/metawear/sensor/cpp/accelerometer.cpp.s
.PHONY : src/metawear/sensor/cpp/accelerometer.s

# target to generate assembly for a file
src/metawear/sensor/cpp/accelerometer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/accelerometer.cpp.s
.PHONY : src/metawear/sensor/cpp/accelerometer.cpp.s

src/metawear/sensor/cpp/accelerometer_bosch.o: src/metawear/sensor/cpp/accelerometer_bosch.cpp.o
.PHONY : src/metawear/sensor/cpp/accelerometer_bosch.o

# target to build an object file
src/metawear/sensor/cpp/accelerometer_bosch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/accelerometer_bosch.cpp.o
.PHONY : src/metawear/sensor/cpp/accelerometer_bosch.cpp.o

src/metawear/sensor/cpp/accelerometer_bosch.i: src/metawear/sensor/cpp/accelerometer_bosch.cpp.i
.PHONY : src/metawear/sensor/cpp/accelerometer_bosch.i

# target to preprocess a source file
src/metawear/sensor/cpp/accelerometer_bosch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/accelerometer_bosch.cpp.i
.PHONY : src/metawear/sensor/cpp/accelerometer_bosch.cpp.i

src/metawear/sensor/cpp/accelerometer_bosch.s: src/metawear/sensor/cpp/accelerometer_bosch.cpp.s
.PHONY : src/metawear/sensor/cpp/accelerometer_bosch.s

# target to generate assembly for a file
src/metawear/sensor/cpp/accelerometer_bosch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/accelerometer_bosch.cpp.s
.PHONY : src/metawear/sensor/cpp/accelerometer_bosch.cpp.s

src/metawear/sensor/cpp/ambientlight_ltr329.o: src/metawear/sensor/cpp/ambientlight_ltr329.cpp.o
.PHONY : src/metawear/sensor/cpp/ambientlight_ltr329.o

# target to build an object file
src/metawear/sensor/cpp/ambientlight_ltr329.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/ambientlight_ltr329.cpp.o
.PHONY : src/metawear/sensor/cpp/ambientlight_ltr329.cpp.o

src/metawear/sensor/cpp/ambientlight_ltr329.i: src/metawear/sensor/cpp/ambientlight_ltr329.cpp.i
.PHONY : src/metawear/sensor/cpp/ambientlight_ltr329.i

# target to preprocess a source file
src/metawear/sensor/cpp/ambientlight_ltr329.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/ambientlight_ltr329.cpp.i
.PHONY : src/metawear/sensor/cpp/ambientlight_ltr329.cpp.i

src/metawear/sensor/cpp/ambientlight_ltr329.s: src/metawear/sensor/cpp/ambientlight_ltr329.cpp.s
.PHONY : src/metawear/sensor/cpp/ambientlight_ltr329.s

# target to generate assembly for a file
src/metawear/sensor/cpp/ambientlight_ltr329.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/ambientlight_ltr329.cpp.s
.PHONY : src/metawear/sensor/cpp/ambientlight_ltr329.cpp.s

src/metawear/sensor/cpp/barometer_bosch.o: src/metawear/sensor/cpp/barometer_bosch.cpp.o
.PHONY : src/metawear/sensor/cpp/barometer_bosch.o

# target to build an object file
src/metawear/sensor/cpp/barometer_bosch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/barometer_bosch.cpp.o
.PHONY : src/metawear/sensor/cpp/barometer_bosch.cpp.o

src/metawear/sensor/cpp/barometer_bosch.i: src/metawear/sensor/cpp/barometer_bosch.cpp.i
.PHONY : src/metawear/sensor/cpp/barometer_bosch.i

# target to preprocess a source file
src/metawear/sensor/cpp/barometer_bosch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/barometer_bosch.cpp.i
.PHONY : src/metawear/sensor/cpp/barometer_bosch.cpp.i

src/metawear/sensor/cpp/barometer_bosch.s: src/metawear/sensor/cpp/barometer_bosch.cpp.s
.PHONY : src/metawear/sensor/cpp/barometer_bosch.s

# target to generate assembly for a file
src/metawear/sensor/cpp/barometer_bosch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/barometer_bosch.cpp.s
.PHONY : src/metawear/sensor/cpp/barometer_bosch.cpp.s

src/metawear/sensor/cpp/gpio.o: src/metawear/sensor/cpp/gpio.cpp.o
.PHONY : src/metawear/sensor/cpp/gpio.o

# target to build an object file
src/metawear/sensor/cpp/gpio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/gpio.cpp.o
.PHONY : src/metawear/sensor/cpp/gpio.cpp.o

src/metawear/sensor/cpp/gpio.i: src/metawear/sensor/cpp/gpio.cpp.i
.PHONY : src/metawear/sensor/cpp/gpio.i

# target to preprocess a source file
src/metawear/sensor/cpp/gpio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/gpio.cpp.i
.PHONY : src/metawear/sensor/cpp/gpio.cpp.i

src/metawear/sensor/cpp/gpio.s: src/metawear/sensor/cpp/gpio.cpp.s
.PHONY : src/metawear/sensor/cpp/gpio.s

# target to generate assembly for a file
src/metawear/sensor/cpp/gpio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/gpio.cpp.s
.PHONY : src/metawear/sensor/cpp/gpio.cpp.s

src/metawear/sensor/cpp/gyro_bosch.o: src/metawear/sensor/cpp/gyro_bosch.cpp.o
.PHONY : src/metawear/sensor/cpp/gyro_bosch.o

# target to build an object file
src/metawear/sensor/cpp/gyro_bosch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/gyro_bosch.cpp.o
.PHONY : src/metawear/sensor/cpp/gyro_bosch.cpp.o

src/metawear/sensor/cpp/gyro_bosch.i: src/metawear/sensor/cpp/gyro_bosch.cpp.i
.PHONY : src/metawear/sensor/cpp/gyro_bosch.i

# target to preprocess a source file
src/metawear/sensor/cpp/gyro_bosch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/gyro_bosch.cpp.i
.PHONY : src/metawear/sensor/cpp/gyro_bosch.cpp.i

src/metawear/sensor/cpp/gyro_bosch.s: src/metawear/sensor/cpp/gyro_bosch.cpp.s
.PHONY : src/metawear/sensor/cpp/gyro_bosch.s

# target to generate assembly for a file
src/metawear/sensor/cpp/gyro_bosch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/gyro_bosch.cpp.s
.PHONY : src/metawear/sensor/cpp/gyro_bosch.cpp.s

src/metawear/sensor/cpp/humidity_bme280.o: src/metawear/sensor/cpp/humidity_bme280.cpp.o
.PHONY : src/metawear/sensor/cpp/humidity_bme280.o

# target to build an object file
src/metawear/sensor/cpp/humidity_bme280.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/humidity_bme280.cpp.o
.PHONY : src/metawear/sensor/cpp/humidity_bme280.cpp.o

src/metawear/sensor/cpp/humidity_bme280.i: src/metawear/sensor/cpp/humidity_bme280.cpp.i
.PHONY : src/metawear/sensor/cpp/humidity_bme280.i

# target to preprocess a source file
src/metawear/sensor/cpp/humidity_bme280.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/humidity_bme280.cpp.i
.PHONY : src/metawear/sensor/cpp/humidity_bme280.cpp.i

src/metawear/sensor/cpp/humidity_bme280.s: src/metawear/sensor/cpp/humidity_bme280.cpp.s
.PHONY : src/metawear/sensor/cpp/humidity_bme280.s

# target to generate assembly for a file
src/metawear/sensor/cpp/humidity_bme280.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/humidity_bme280.cpp.s
.PHONY : src/metawear/sensor/cpp/humidity_bme280.cpp.s

src/metawear/sensor/cpp/magnetometer_bmm150.o: src/metawear/sensor/cpp/magnetometer_bmm150.cpp.o
.PHONY : src/metawear/sensor/cpp/magnetometer_bmm150.o

# target to build an object file
src/metawear/sensor/cpp/magnetometer_bmm150.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/magnetometer_bmm150.cpp.o
.PHONY : src/metawear/sensor/cpp/magnetometer_bmm150.cpp.o

src/metawear/sensor/cpp/magnetometer_bmm150.i: src/metawear/sensor/cpp/magnetometer_bmm150.cpp.i
.PHONY : src/metawear/sensor/cpp/magnetometer_bmm150.i

# target to preprocess a source file
src/metawear/sensor/cpp/magnetometer_bmm150.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/magnetometer_bmm150.cpp.i
.PHONY : src/metawear/sensor/cpp/magnetometer_bmm150.cpp.i

src/metawear/sensor/cpp/magnetometer_bmm150.s: src/metawear/sensor/cpp/magnetometer_bmm150.cpp.s
.PHONY : src/metawear/sensor/cpp/magnetometer_bmm150.s

# target to generate assembly for a file
src/metawear/sensor/cpp/magnetometer_bmm150.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/magnetometer_bmm150.cpp.s
.PHONY : src/metawear/sensor/cpp/magnetometer_bmm150.cpp.s

src/metawear/sensor/cpp/multichanneltemperature.o: src/metawear/sensor/cpp/multichanneltemperature.cpp.o
.PHONY : src/metawear/sensor/cpp/multichanneltemperature.o

# target to build an object file
src/metawear/sensor/cpp/multichanneltemperature.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/multichanneltemperature.cpp.o
.PHONY : src/metawear/sensor/cpp/multichanneltemperature.cpp.o

src/metawear/sensor/cpp/multichanneltemperature.i: src/metawear/sensor/cpp/multichanneltemperature.cpp.i
.PHONY : src/metawear/sensor/cpp/multichanneltemperature.i

# target to preprocess a source file
src/metawear/sensor/cpp/multichanneltemperature.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/multichanneltemperature.cpp.i
.PHONY : src/metawear/sensor/cpp/multichanneltemperature.cpp.i

src/metawear/sensor/cpp/multichanneltemperature.s: src/metawear/sensor/cpp/multichanneltemperature.cpp.s
.PHONY : src/metawear/sensor/cpp/multichanneltemperature.s

# target to generate assembly for a file
src/metawear/sensor/cpp/multichanneltemperature.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/multichanneltemperature.cpp.s
.PHONY : src/metawear/sensor/cpp/multichanneltemperature.cpp.s

src/metawear/sensor/cpp/sensor_fusion.o: src/metawear/sensor/cpp/sensor_fusion.cpp.o
.PHONY : src/metawear/sensor/cpp/sensor_fusion.o

# target to build an object file
src/metawear/sensor/cpp/sensor_fusion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/sensor_fusion.cpp.o
.PHONY : src/metawear/sensor/cpp/sensor_fusion.cpp.o

src/metawear/sensor/cpp/sensor_fusion.i: src/metawear/sensor/cpp/sensor_fusion.cpp.i
.PHONY : src/metawear/sensor/cpp/sensor_fusion.i

# target to preprocess a source file
src/metawear/sensor/cpp/sensor_fusion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/sensor_fusion.cpp.i
.PHONY : src/metawear/sensor/cpp/sensor_fusion.cpp.i

src/metawear/sensor/cpp/sensor_fusion.s: src/metawear/sensor/cpp/sensor_fusion.cpp.s
.PHONY : src/metawear/sensor/cpp/sensor_fusion.s

# target to generate assembly for a file
src/metawear/sensor/cpp/sensor_fusion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/sensor_fusion.cpp.s
.PHONY : src/metawear/sensor/cpp/sensor_fusion.cpp.s

src/metawear/sensor/cpp/serialpassthrough.o: src/metawear/sensor/cpp/serialpassthrough.cpp.o
.PHONY : src/metawear/sensor/cpp/serialpassthrough.o

# target to build an object file
src/metawear/sensor/cpp/serialpassthrough.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/serialpassthrough.cpp.o
.PHONY : src/metawear/sensor/cpp/serialpassthrough.cpp.o

src/metawear/sensor/cpp/serialpassthrough.i: src/metawear/sensor/cpp/serialpassthrough.cpp.i
.PHONY : src/metawear/sensor/cpp/serialpassthrough.i

# target to preprocess a source file
src/metawear/sensor/cpp/serialpassthrough.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/serialpassthrough.cpp.i
.PHONY : src/metawear/sensor/cpp/serialpassthrough.cpp.i

src/metawear/sensor/cpp/serialpassthrough.s: src/metawear/sensor/cpp/serialpassthrough.cpp.s
.PHONY : src/metawear/sensor/cpp/serialpassthrough.s

# target to generate assembly for a file
src/metawear/sensor/cpp/serialpassthrough.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/serialpassthrough.cpp.s
.PHONY : src/metawear/sensor/cpp/serialpassthrough.cpp.s

src/metawear/sensor/cpp/switch.o: src/metawear/sensor/cpp/switch.cpp.o
.PHONY : src/metawear/sensor/cpp/switch.o

# target to build an object file
src/metawear/sensor/cpp/switch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/switch.cpp.o
.PHONY : src/metawear/sensor/cpp/switch.cpp.o

src/metawear/sensor/cpp/switch.i: src/metawear/sensor/cpp/switch.cpp.i
.PHONY : src/metawear/sensor/cpp/switch.i

# target to preprocess a source file
src/metawear/sensor/cpp/switch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/switch.cpp.i
.PHONY : src/metawear/sensor/cpp/switch.cpp.i

src/metawear/sensor/cpp/switch.s: src/metawear/sensor/cpp/switch.cpp.s
.PHONY : src/metawear/sensor/cpp/switch.s

# target to generate assembly for a file
src/metawear/sensor/cpp/switch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/switch.cpp.s
.PHONY : src/metawear/sensor/cpp/switch.cpp.s

src/metawear/sensor/cpp/utils.o: src/metawear/sensor/cpp/utils.cpp.o
.PHONY : src/metawear/sensor/cpp/utils.o

# target to build an object file
src/metawear/sensor/cpp/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/utils.cpp.o
.PHONY : src/metawear/sensor/cpp/utils.cpp.o

src/metawear/sensor/cpp/utils.i: src/metawear/sensor/cpp/utils.cpp.i
.PHONY : src/metawear/sensor/cpp/utils.i

# target to preprocess a source file
src/metawear/sensor/cpp/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/utils.cpp.i
.PHONY : src/metawear/sensor/cpp/utils.cpp.i

src/metawear/sensor/cpp/utils.s: src/metawear/sensor/cpp/utils.cpp.s
.PHONY : src/metawear/sensor/cpp/utils.s

# target to generate assembly for a file
src/metawear/sensor/cpp/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metawear.dir/build.make CMakeFiles/metawear.dir/src/metawear/sensor/cpp/utils.cpp.s
.PHONY : src/metawear/sensor/cpp/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... metawear"
	@echo "... src/metawear/core/cpp/anonymous_datasignal.o"
	@echo "... src/metawear/core/cpp/anonymous_datasignal.i"
	@echo "... src/metawear/core/cpp/anonymous_datasignal.s"
	@echo "... src/metawear/core/cpp/datasignal.o"
	@echo "... src/metawear/core/cpp/datasignal.i"
	@echo "... src/metawear/core/cpp/datasignal.s"
	@echo "... src/metawear/core/cpp/debug.o"
	@echo "... src/metawear/core/cpp/debug.i"
	@echo "... src/metawear/core/cpp/debug.s"
	@echo "... src/metawear/core/cpp/event.o"
	@echo "... src/metawear/core/cpp/event.i"
	@echo "... src/metawear/core/cpp/event.s"
	@echo "... src/metawear/core/cpp/logging.o"
	@echo "... src/metawear/core/cpp/logging.i"
	@echo "... src/metawear/core/cpp/logging.s"
	@echo "... src/metawear/core/cpp/macro.o"
	@echo "... src/metawear/core/cpp/macro.i"
	@echo "... src/metawear/core/cpp/macro.s"
	@echo "... src/metawear/core/cpp/moduleinfo.o"
	@echo "... src/metawear/core/cpp/moduleinfo.i"
	@echo "... src/metawear/core/cpp/moduleinfo.s"
	@echo "... src/metawear/core/cpp/responseheader.o"
	@echo "... src/metawear/core/cpp/responseheader.i"
	@echo "... src/metawear/core/cpp/responseheader.s"
	@echo "... src/metawear/core/cpp/settings.o"
	@echo "... src/metawear/core/cpp/settings.i"
	@echo "... src/metawear/core/cpp/settings.s"
	@echo "... src/metawear/core/cpp/timer.o"
	@echo "... src/metawear/core/cpp/timer.i"
	@echo "... src/metawear/core/cpp/timer.s"
	@echo "... src/metawear/core/cpp/version.o"
	@echo "... src/metawear/core/cpp/version.i"
	@echo "... src/metawear/core/cpp/version.s"
	@echo "... src/metawear/dfu/cpp/dfu_operations.o"
	@echo "... src/metawear/dfu/cpp/dfu_operations.i"
	@echo "... src/metawear/dfu/cpp/dfu_operations.s"
	@echo "... src/metawear/dfu/cpp/dfu_operations_details.o"
	@echo "... src/metawear/dfu/cpp/dfu_operations_details.i"
	@echo "... src/metawear/dfu/cpp/dfu_operations_details.s"
	@echo "... src/metawear/dfu/cpp/dfu_utility.o"
	@echo "... src/metawear/dfu/cpp/dfu_utility.i"
	@echo "... src/metawear/dfu/cpp/dfu_utility.s"
	@echo "... src/metawear/dfu/cpp/file_operations.o"
	@echo "... src/metawear/dfu/cpp/file_operations.i"
	@echo "... src/metawear/dfu/cpp/file_operations.s"
	@echo "... src/metawear/dfu/cpp/miniz.o"
	@echo "... src/metawear/dfu/cpp/miniz.i"
	@echo "... src/metawear/dfu/cpp/miniz.s"
	@echo "... src/metawear/impl/cpp/datainterpreter.o"
	@echo "... src/metawear/impl/cpp/datainterpreter.i"
	@echo "... src/metawear/impl/cpp/datainterpreter.s"
	@echo "... src/metawear/impl/cpp/metawearboard.o"
	@echo "... src/metawear/impl/cpp/metawearboard.i"
	@echo "... src/metawear/impl/cpp/metawearboard.s"
	@echo "... src/metawear/peripheral/cpp/haptic.o"
	@echo "... src/metawear/peripheral/cpp/haptic.i"
	@echo "... src/metawear/peripheral/cpp/haptic.s"
	@echo "... src/metawear/peripheral/cpp/ibeacon.o"
	@echo "... src/metawear/peripheral/cpp/ibeacon.i"
	@echo "... src/metawear/peripheral/cpp/ibeacon.s"
	@echo "... src/metawear/peripheral/cpp/led.o"
	@echo "... src/metawear/peripheral/cpp/led.i"
	@echo "... src/metawear/peripheral/cpp/led.s"
	@echo "... src/metawear/platform/cpp/async_creator.o"
	@echo "... src/metawear/platform/cpp/async_creator.i"
	@echo "... src/metawear/platform/cpp/async_creator.s"
	@echo "... src/metawear/platform/cpp/memory.o"
	@echo "... src/metawear/platform/cpp/memory.i"
	@echo "... src/metawear/platform/cpp/memory.s"
	@echo "... src/metawear/platform/cpp/task.o"
	@echo "... src/metawear/platform/cpp/task.i"
	@echo "... src/metawear/platform/cpp/task.s"
	@echo "... src/metawear/platform/cpp/threadpool.o"
	@echo "... src/metawear/platform/cpp/threadpool.i"
	@echo "... src/metawear/platform/cpp/threadpool.s"
	@echo "... src/metawear/processor/cpp/dataprocessor.o"
	@echo "... src/metawear/processor/cpp/dataprocessor.i"
	@echo "... src/metawear/processor/cpp/dataprocessor.s"
	@echo "... src/metawear/processor/cpp/dataprocessor_config.o"
	@echo "... src/metawear/processor/cpp/dataprocessor_config.i"
	@echo "... src/metawear/processor/cpp/dataprocessor_config.s"
	@echo "... src/metawear/sensor/cpp/accelerometer.o"
	@echo "... src/metawear/sensor/cpp/accelerometer.i"
	@echo "... src/metawear/sensor/cpp/accelerometer.s"
	@echo "... src/metawear/sensor/cpp/accelerometer_bosch.o"
	@echo "... src/metawear/sensor/cpp/accelerometer_bosch.i"
	@echo "... src/metawear/sensor/cpp/accelerometer_bosch.s"
	@echo "... src/metawear/sensor/cpp/ambientlight_ltr329.o"
	@echo "... src/metawear/sensor/cpp/ambientlight_ltr329.i"
	@echo "... src/metawear/sensor/cpp/ambientlight_ltr329.s"
	@echo "... src/metawear/sensor/cpp/barometer_bosch.o"
	@echo "... src/metawear/sensor/cpp/barometer_bosch.i"
	@echo "... src/metawear/sensor/cpp/barometer_bosch.s"
	@echo "... src/metawear/sensor/cpp/gpio.o"
	@echo "... src/metawear/sensor/cpp/gpio.i"
	@echo "... src/metawear/sensor/cpp/gpio.s"
	@echo "... src/metawear/sensor/cpp/gyro_bosch.o"
	@echo "... src/metawear/sensor/cpp/gyro_bosch.i"
	@echo "... src/metawear/sensor/cpp/gyro_bosch.s"
	@echo "... src/metawear/sensor/cpp/humidity_bme280.o"
	@echo "... src/metawear/sensor/cpp/humidity_bme280.i"
	@echo "... src/metawear/sensor/cpp/humidity_bme280.s"
	@echo "... src/metawear/sensor/cpp/magnetometer_bmm150.o"
	@echo "... src/metawear/sensor/cpp/magnetometer_bmm150.i"
	@echo "... src/metawear/sensor/cpp/magnetometer_bmm150.s"
	@echo "... src/metawear/sensor/cpp/multichanneltemperature.o"
	@echo "... src/metawear/sensor/cpp/multichanneltemperature.i"
	@echo "... src/metawear/sensor/cpp/multichanneltemperature.s"
	@echo "... src/metawear/sensor/cpp/sensor_fusion.o"
	@echo "... src/metawear/sensor/cpp/sensor_fusion.i"
	@echo "... src/metawear/sensor/cpp/sensor_fusion.s"
	@echo "... src/metawear/sensor/cpp/serialpassthrough.o"
	@echo "... src/metawear/sensor/cpp/serialpassthrough.i"
	@echo "... src/metawear/sensor/cpp/serialpassthrough.s"
	@echo "... src/metawear/sensor/cpp/switch.o"
	@echo "... src/metawear/sensor/cpp/switch.i"
	@echo "... src/metawear/sensor/cpp/switch.s"
	@echo "... src/metawear/sensor/cpp/utils.o"
	@echo "... src/metawear/sensor/cpp/utils.i"
	@echo "... src/metawear/sensor/cpp/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

